[theme]
primaryColor = "#002db3"
backgroundColor = "#f4f6fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
